Created Login and Forgotpassword pages and fixed styles(cards, header, aside)
fabricadesoftware-ifc/fabricaClass_frontEnd pull request #46
Opened 2024-09-05 17:34 UTC by Vinyzada

2024-09-26 16:17 UTC, Wecreds requested changes

2024-09-26 16:17 UTC, Wecreds commented on src/components/Cards/ItemCard.vue
O nome da classe(linha 27) esta sendo mostrado com uma cor meio cinza claro, quando era pra ser preto.
![image](https://github.com/user-attachments/assets/b3b9b5a6-1e75-40a8-8ac8-2a469cb96dd5)

2024-09-26 16:17 UTC, Wecreds commented on src/components/Cards/CardsComp.vue
> +    <main class>
```suggestion
    <main>
```

2024-09-26 16:17 UTC, Wecreds commented on src/components/templates/large/forgotPasswordComps/confirmEmailComp.vue
> +</script>
```suggestion

```

2024-09-26 16:17 UTC, Wecreds commented on src/components/templates/large/forgotPasswordComps/confirmEmailComp.vue
> +</style>
```suggestion

```

2024-09-26 16:17 UTC, Wecreds commented on src/views/auth/ForgotPasswordView.vue
> +</template>
cade todo o template?

2024-09-26 16:17 UTC, Wecreds commented on src/views/auth/ForgotPasswordView.vue
> +</style>
```suggestion

```

2024-09-27 18:47 UTC, Vinyzada commented on src/views/auth/ForgotPasswordView.vue
> +</template>
os componentes irão alternar conforme as validações irão sendo executadas

2024-10-01 14:46 UTC, Wecreds approved these changes
tudo certo, só fazer rebase e mergar.

2024-10-03 14:03 UTC, merged